cursor            #ffb4a3
cursor_text_color #561f12

foreground            #f1dfdb
background            #140c0a
selection_foreground  #442a23
selection_background  #e7bdb4
url_color             #e7bdb4

#: black
color0  #271d1b
color8  #322825
#: red
color1  #ffb4ab
color9  #ffdad6
#: green
color2  #ffb4a3
color10 #ffdad2
#: yellow
color3  #dbc58c
color11 #f8e1a6
#: blue
color4  #cebdfe
color12 #4c3e76
#: magenta
color5  #fcb0d5
color13 #6c3353
#: cyan
color6  #84d5c4
color14 #005045
#: white
color7  #d8c2bd
color15 #f1dfdb

mark1_foreground #3a0a02
mark1_background #ffdad2
mark2_foreground #2c1510
mark2_background #ffdad2
mark3_foreground #241a00
mark3_background #f8e1a6

active_tab_foreground   #561f12
active_tab_background   #ffb4a3
inactive_tab_foreground #ffdad2
inactive_tab_background #733426

active_border_color   #ffb4a3
inactive_border_color #561f12
