color0 #1b1013
color1 #ffb4ab
color2 #ceca7e
color3 #f6b8a8
color4 #80d1f5
color5 #ceca7e
color6 #f6b8a8
color7 #f3dde1
color8 #a48a8f
color9 #ffb4ab
color10 #ceca7e
color11 #f6b8a8
color12 #80d1f5
color13 #ceca7e
color14 #f6b8a8
color15 #f3dde1

cursor                #f3dde1
cursor_text_color     #1b1013
background            #1b1013
foreground            #f3dde1
selection_foreground  #ddbfc5
selection_background  #564146
url_color             #80d1f5